### ISSUE TITLE
Visual Story Template

### ISSUE THREAD

**Issue by shraddha-kesari** [quintype/quintype-amp#301]
1. Visual story will be served as a story template
2. All story elements will be inside `<amp-story-grid-layer>` tag.
3. Each card will be wrapped with `<amp-story-page>` tag.
4. All cards will be wrapped with `<amp-story>` tag.
<img width="938" alt="Screenshot 2020-10-19 at 11 02 54 AM" src="https://user-images.githubusercontent.com/18402707/96405397-d4864e80-11fa-11eb-9d21-de73111ab37b.png">

check here how pages can be designed by adding attributes [https://amp.dev/documentation/guides-and-tutorials/start/visual_story/add_more_pages/?format=websites](url)

**Default Template**

First page will have the header card. Header card consists of HeroImage,  headline and author name. 
**Hero Image** - occupies the whole page as a background. This will be the first layer. 
These three will be in the second layer. 
**Headline** - comes at the bottom of the page. This will be the third layer.  
So, in total header card will have 3 layers. 
 
Second page will hold the first story card. Each card will be a new page. Each story element in the card will be in a different layer. 
If the card has a text story element, it will be displayed at the bottom of the page. 
If the card includes an Image, it will be as a background of that page.

<img width="349" alt="Screenshot 2020-10-21 at 6 03 53 PM" src="https://user-images.githubusercontent.com/18402707/96720122-03055480-13c8-11eb-9bea-b0d94cc68a6f.png">

Other elements we need to discuss the places and standardise them. 

**Tasks:**

- [x] Enable visual story template in the backend 

- [x] Enable Visual story template in amp lib staging instance

- [ ] Route existing visual amp stories to amp lib and probably add a 301 redirect on those routes

- [ ] Restructure Ahead's code by removing the separate api call for visual story.

- [ ] Implement Visual story as a story template in Amp. 

- [ ] Spike the above in  local.

- [ ] Discuss with the design team for standard design implementation with animations. 

- [ ] Depending on the design, structure the template.

**Questions** 

1. Will overrides be provided for this template ?? For MVP, we will provide only default template as same as ahead.

2. What about ads and slots ?? Use amp auto ads

**Unknowns**

1. What collection to use for bookend ? 

2. The amp html url of the non amp visual story must be pointing to amp story url and canonical url of amp story must be pointing to non-amp story. How will we get the amp html url ?
